// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Superdigital.Backend.ContaCorrente.Data;
using Superdigital.Backend.ContaCorrente.Data.Context;

namespace Superdigital.Backend.ContaCorrente.Migrations
{
    [DbContext(typeof(ContaCorrenteContext))]
    [Migration("20190112154013_ContaCorrenteDb")]
    partial class ContaCorrenteDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Superdigital.Backend.ContaCorrente.Domain.ContaCliente", b =>
                {
                    b.Property<int>("ContaClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(100);

                    b.Property<double>("Saldo");

                    b.HasKey("ContaClienteId");

                    b.ToTable("ContasClientes");
                });

            modelBuilder.Entity("Superdigital.Backend.ContaCorrente.Domain.Lancamento", b =>
                {
                    b.Property<int>("LancamentoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContaClienteId");

                    b.Property<int>("TipoOperacao");

                    b.Property<double>("Valor");

                    b.HasKey("LancamentoId");

                    b.HasIndex("ContaClienteId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("Superdigital.Backend.ContaCorrente.Domain.Lancamento", b =>
                {
                    b.HasOne("Superdigital.Backend.ContaCorrente.Domain.ContaCliente", "ContaCliente")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaClienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
